/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import banco_de_dados.BancoPopular;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Aluno;

/**
 *
 * @author Familia
 */
public class TelaInserirAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaInserirAluno
     */
    BancoPopular banco;
    
    public TelaInserirAluno(BancoPopular banco) throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        this.banco = banco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salvarButton = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        textFieldCPF = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        labelMatricula = new javax.swing.JLabel();
        textFieldMatricula = new javax.swing.JTextField();
        textFieldNome = new javax.swing.JTextField();
        comboBoxSexo = new javax.swing.JComboBox<>();
        labelSexo = new javax.swing.JLabel();
        labelRH = new javax.swing.JLabel();
        comboBoxRH = new javax.swing.JComboBox<>();
        labelNascimento = new javax.swing.JLabel();
        textFieldNascimento = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        textFieldCelular = new javax.swing.JTextField();
        labelCelular = new javax.swing.JLabel();
        textFieldTelefone = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        textFieldEndereco = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        labelAlergia = new javax.swing.JLabel();
        textFieldAlergia = new javax.swing.JTextField();
        labelDoenca = new javax.swing.JLabel();
        textFieldDoenca = new javax.swing.JTextField();
        labelMedicacao = new javax.swing.JLabel();
        textFieldMedicacao = new javax.swing.JTextField();
        labelVinculo = new javax.swing.JLabel();
        comboBoxVinculo = new javax.swing.JComboBox<>();
        voltarButton = new javax.swing.JButton();
        labelEmergencia = new javax.swing.JLabel();
        textFieldEmergencia = new javax.swing.JTextField();
        limparButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        labelNome.setText("Nome:");

        textFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCPFActionPerformed(evt);
            }
        });

        labelCPF.setText("CPF:");

        labelMatricula.setText("Matrícula:");

        textFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMatriculaActionPerformed(evt);
            }
        });

        textFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeActionPerformed(evt);
            }
        });

        comboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        comboBoxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSexoActionPerformed(evt);
            }
        });

        labelSexo.setText("Sexo:");

        labelRH.setText("RH:");

        comboBoxRH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-", "N", " " }));
        comboBoxRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRHActionPerformed(evt);
            }
        });

        labelNascimento.setText("Data de nascimento:");

        textFieldNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNascimentoActionPerformed(evt);
            }
        });

        labelTelefone.setText("Telefone:");

        textFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCelularActionPerformed(evt);
            }
        });

        labelCelular.setText("Celular:");

        textFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefoneActionPerformed(evt);
            }
        });

        labelEmail.setText("Email:");

        textFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
            }
        });

        textFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEnderecoActionPerformed(evt);
            }
        });

        labelEndereco.setText("Endereço:");

        labelAlergia.setText("Alergia:");

        textFieldAlergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlergiaActionPerformed(evt);
            }
        });

        labelDoenca.setText("Doença:");

        textFieldDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDoencaActionPerformed(evt);
            }
        });

        labelMedicacao.setText("Medicaçao:");

        textFieldMedicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMedicacaoActionPerformed(evt);
            }
        });

        labelVinculo.setText("Vínculo:");

        comboBoxVinculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASSOCIADO", "ATLETA", "ATLETA ASSOCIADO" }));
        comboBoxVinculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVinculoActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        labelEmergencia.setText("Emergência: ");

        textFieldEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmergenciaActionPerformed(evt);
            }
        });

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/3asm.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(salvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelEmergencia)
                                        .addComponent(labelMedicacao)
                                        .addComponent(labelAlergia))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(textFieldAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(labelDoenca)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(textFieldDoenca))
                                        .addComponent(textFieldMedicacao, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldEmergencia, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelEndereco)
                                        .addComponent(labelEmail))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldEndereco)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelCelular)
                                                .addGap(18, 18, 18)
                                                .addComponent(textFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelVinculo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(comboBoxVinculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(293, 293, 293)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelTelefone)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelMatricula)
                                        .addComponent(labelNome)
                                        .addComponent(labelSexo))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(comboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(labelRH)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(comboBoxRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(labelCPF)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(textFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNascimento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textFieldNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMatricula)
                            .addComponent(textFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCPF)
                            .addComponent(textFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSexo)
                            .addComponent(comboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRH)
                            .addComponent(comboBoxRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNascimento)
                            .addComponent(textFieldNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCelular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco)
                    .addComponent(textFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlergia)
                    .addComponent(textFieldAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDoenca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMedicacao)
                    .addComponent(textFieldMedicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmergencia)
                    .addComponent(textFieldEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVinculo)
                    .addComponent(comboBoxVinculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButton)
                    .addComponent(voltarButton)
                    .addComponent(limparButton))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("lendo o aluno");
        Aluno aluno = new Aluno();
        aluno.setNome(textFieldNome.getText());
        aluno.setMatricula(Long.parseLong(textFieldMatricula.getText()));
        aluno.setCpf(Long.parseLong(textFieldCPF.getText()));
        aluno.setCelular(textFieldCelular.getText());
        aluno.setTelefone(textFieldTelefone.getText());
        aluno.setNascimento(textFieldNascimento.getText());
        aluno.setEmail(textFieldEmail.getText());
        aluno.setEndereco(textFieldEndereco.getText());
        aluno.setDoença(textFieldDoenca.getText());
        aluno.setMedicacao(textFieldMedicacao.getText());
        aluno.setAlergia(textFieldAlergia.getText());
        aluno.setEmergencia(textFieldEmergencia.getText());
        
        switch(comboBoxRH.getSelectedIndex()){
            case 0:
                aluno.setRh("A+");
            break;
            case 1:
                aluno.setRh("B+");
            break;
            case 2:
                aluno.setRh("AB+");
            break;
            case 3:
                aluno.setRh("O+");
            break;
            case 4:
                aluno.setRh("A-");
            break;
            case 5:
                aluno.setRh("B-");
            break;
            case 6:
                aluno.setRh("AB-");
            break;
            case 7:
                aluno.setRh("O-");
            break;
            case 8:
                aluno.setRh("N");
            break;
        }
        
        aluno.setSexo((short)comboBoxSexo.getSelectedIndex());
        aluno.setVinculo((short)comboBoxVinculo.getSelectedIndex());
        aluno.exibirImportante();
        
        //Tratamento  de erros do limite do campo excedido
        ArrayList<String> errosEntrada  = new ArrayList<String>();
        
        if (textFieldNome.getText().length() > 60){
            errosEntrada.add("Tamanho máximo do campo Nome excedido!");
        }
        if(textFieldEmail.getText().length() > 60){
            errosEntrada.add("Tamanho máximo do campo Email excedido!");
        }
        if(textFieldEmergencia.getText().length() > 60){
            errosEntrada.add("Tamanho máximo do campo Emergência excedido!");
        }
        if(textFieldEndereco.getText().length() > 60){
            errosEntrada.add("Tamanho máximo do campo Endereço excedido!");
        }
        if(textFieldAlergia.getText().length() > 60){
            errosEntrada.add("Tamanho máximo do campo Alergia excedido!");
        }
        if(textFieldMedicacao.getText().length() > 50){
            errosEntrada.add("Tamanho máximo do campo Medicação excedido!");
        }
        if(textFieldCelular.getText().length() > 9){
            errosEntrada.add("Tamanho máximo do campo Celular excedido!");
        }
        if(textFieldTelefone.getText().length() > 8){
            errosEntrada.add("Tamanho máximo do campo Telefone excedido!");
        }
        if(textFieldNascimento.getText().length() > 8){
            errosEntrada.add("Tamanho máximo do campo Nascimento excedido!");
        }
        if(textFieldDoenca.getText().length() > 60){
            errosEntrada.add("Tamanho máximo do campo Doença excedido!");
        }
        
        if(errosEntrada.size() > 0){
            for (int i = 0; i < errosEntrada.size(); i++) {
                JOptionPane.showMessageDialog(this.getContentPane(), errosEntrada.get(i), "Erro", JOptionPane.ERROR_MESSAGE);
            }    
        }else{
            try {
            if(banco.inserir(aluno)){
                JOptionPane.showMessageDialog(this.getContentPane(), "Aluno inserido");
                //limparCampos();
            }else{
                JOptionPane.showMessageDialog(this.getContentPane(), "Usuario ja está no banco de dados");
            }
            
            /*Caso tenha inserido avisar que foi inserido e voltar pro menu principal, caso contrario avisa que ja existe*/
        } catch (IOException ex) {
            Logger.getLogger(TelaInserirAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
        //Exibção dos erros pelas Janelas
        if(errosEntrada.size() > 0){
            for (int i = 0; i < errosEntrada.size(); i++) {
                JOptionPane.showMessageDialog(this.getContentPane(), errosEntrada.get(i), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_salvarButtonActionPerformed
    
    private void limparCampos(){
        textFieldAlergia.setText("");
        textFieldCPF.setText("");
        textFieldCelular.setText("");
        textFieldDoenca.setText("");
        textFieldEmail.setText("");
        textFieldEmergencia.setText("");
        textFieldEndereco.setText("");
        textFieldMatricula.setText("");
        textFieldMedicacao.setText("");
        textFieldNascimento.setText("");
        textFieldNome.setText("");
        textFieldTelefone.setText("");
    }
    private void textFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCPFActionPerformed

    private void textFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMatriculaActionPerformed

    private void textFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeActionPerformed

    private void comboBoxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSexoActionPerformed

    private void comboBoxRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRHActionPerformed

    private void textFieldNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNascimentoActionPerformed

    private void textFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCelularActionPerformed

    private void textFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTelefoneActionPerformed

    private void textFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailActionPerformed

    private void textFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEnderecoActionPerformed

    private void textFieldAlergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlergiaActionPerformed

    private void textFieldDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDoencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDoencaActionPerformed

    private void textFieldMedicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMedicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMedicacaoActionPerformed

    private void comboBoxVinculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVinculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxVinculoActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new TelaInicial(this.banco).setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void textFieldEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmergenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmergenciaActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        limparCampos();
    }//GEN-LAST:event_limparButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxRH;
    private javax.swing.JComboBox<String> comboBoxSexo;
    private javax.swing.JComboBox<String> comboBoxVinculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAlergia;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelDoenca;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmergencia;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelMedicacao;
    private javax.swing.JLabel labelNascimento;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRH;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelVinculo;
    private javax.swing.JButton limparButton;
    private javax.swing.JButton salvarButton;
    private javax.swing.JTextField textFieldAlergia;
    private javax.swing.JTextField textFieldCPF;
    private javax.swing.JTextField textFieldCelular;
    private javax.swing.JTextField textFieldDoenca;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldEmergencia;
    private javax.swing.JTextField textFieldEndereco;
    private javax.swing.JTextField textFieldMatricula;
    private javax.swing.JTextField textFieldMedicacao;
    private javax.swing.JTextField textFieldNascimento;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldTelefone;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
